[package]
name = "chip-8-emulator"
version = "0.1.0"
authors = ["Njord0 <52111877+Njord0@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"